MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('author/<int:author_id>/', views.author_posts, name='author_posts'),
]

blog/models.py
from django.db import models
import datetime as dt

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('Author', on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return self.title
    
    def published_recently(self):
        return self.published_date >= dt.datetime.now() - dt.timedelta(days=7)
    

class Author(models.Model):
    name = models.CharField(max_length=50)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author_name = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author_name} on {self.post.title}'

blog/views.py
from django.shortcuts import render
from blog.models import Post, Author

# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', context={'posts': posts})

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    return render(request, 'blog/post_detail.html', context={'post': post})

def author_posts(request, author_id):
    author = Author.objects.get(id=author_id)
    posts = author.posts.all()
    return render(request, 'blog/author_post_list.html', context={'posts': posts, 'author': author})

templates/blog/author_post_list.html
{% extends 'blog/post_list.html' %}

{% block title %}Posts by {{ author.name }}{% endblock %}

{% block body_title %}Posts by {{ author.name }}{% endblock %}

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post detail</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <h4>Author: <a href="{% url 'blog:author_posts' post.author.id %}">{{post.author}}</a></h4>
    <h4>Published on: {{post.published_date}}</h4>
    <h4>Content: {{post.content}}</h4>
    <h3>Коментарі:</h3>
    <ul>
        {% for comment in post.comments.all %}
            <li>
                <div>
                    <h4>{{ comment.author_name }}</h4>
                    <p>{{ comment.created_date}}</p>
                </div>
                <p>{{ comment.text }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Posts{% endblock %}</title>
</head>
<body>
    <h1>{% block body_title %}Posts{% endblock %}</h1>
    <ul>
        {% for post in posts %}
            <li>
                <p><a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a> ({{post.published_date}})</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>